import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';

const output = '.impeccable/review/final';
await mkdir(output, { recursive: true });
const browser = await chromium.launch({
  executablePath: process.env.CHROMIUM_PATH || '/home/marco/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome',
  headless: true,
  args: ['--no-sandbox', '--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'],
});
const errors = [];
const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, reducedMotion: 'reduce' });
const page = await context.newPage();
page.on('pageerror', error => errors.push(error.message));
await page.goto('http://127.0.0.1:5173/', { waitUntil: 'networkidle' });
await page.evaluate(() => document.fonts.ready);
await page.waitForTimeout(600);
await page.screenshot({ path: `${output}/desktop.png`, fullPage: true });
assert.equal(await page.locator('.orbital-scene canvas').count(), 1, '3D scene renders');
assert.equal(await page.locator('.task-tile').count(), 4);
assert.equal(await page.getByRole('button', { name: 'Conferma decisione', exact: true }).isDisabled(), true);
await page.getByRole('button', { name: /Anche chi non ha un account/ }).click();
assert.equal(await page.locator('.task-tile.task-warning').count(), 4, 'Preview propagates through all tasks');
await page.screenshot({ path: `${output}/decision-preview.png`, fullPage: true });
await page.getByRole('button', { name: 'Conferma decisione', exact: true }).click();
await page.getByRole('heading', { name: 'Quanto dura una prenotazione?' }).waitFor();
await page.getByRole('button', { name: /Sempre 30 minuti/ }).click();
await page.getByRole('button', { name: 'Conferma decisione', exact: true }).click();
await page.getByRole('heading', { name: 'Fino a quando si può cancellare?' }).waitFor();
await page.getByRole('button', { name: /Fino all’inizio della riunione|Fino all'inizio della riunione/ }).click();
await page.getByRole('button', { name: 'Conferma decisione', exact: true }).click();
await page.getByRole('heading', { name: /Missione chiarita/ }).waitFor();
await page.getByRole('button', { name: 'Chiudi notifica' }).click();
await page.waitForTimeout(650);
await page.screenshot({ path: `${output}/mission-complete.png`, fullPage: true });
await page.getByRole('button', { name: 'Esplora il riepilogo' }).click();
assert.match(await page.locator('.brief-output').innerText(), /ospiti senza account/);
const downloadPromise = page.waitForEvent('download');
await page.getByRole('button', { name: /Scarica .md/ }).click();
const download = await downloadPromise;
assert.equal(download.suggestedFilename(), 'specops-brief.md');
await page.keyboard.press('Escape');
await page.getByRole('button', { name: /Decisione 1, risposta acquisita/ }).click();
await page.getByRole('button', { name: /Solo utenti registrati/ }).click();
await page.getByRole('button', { name: 'Aggiorna decisione' }).click();
await page.getByRole('heading', { name: /Missione chiarita/ }).waitFor();
assert.equal(await page.locator('.task-tile.task-warning').count(), 2, 'Undoing access decision preserves cancellation impact');
await page.reload({ waitUntil: 'networkidle' });
await page.getByRole('heading', { name: /Missione chiarita/ }).waitFor();
assert.equal(await page.locator('.task-tile.task-warning').count(), 2, 'Decisions survive reload');
await page.getByRole('button', { name: 'Nuova missione' }).click();
await page.route('http://localhost:3001/api/analyze', route => route.abort('connectionrefused'));
await page.getByRole('button', { name: 'Trova le decisioni' }).click();
await page.getByRole('alert').filter({ hasText: 'Core non raggiungibile' }).waitFor();
assert.equal(await page.locator('dialog[open]').count(), 1, 'Failure leaves inputs visible');
await page.getByRole('button', { name: 'Carica scenario demo' }).click();
await page.getByRole('heading', { name: 'Chi può prenotare?' }).waitFor();
await page.getByRole('button', { name: 'Chiudi notifica' }).click();
assert.equal(await page.locator('.task-tile.task-warning').count(), 0);
await page.setViewportSize({ width: 1366, height: 768 });
await page.waitForTimeout(400);
await page.screenshot({ path: `${output}/compact-desktop.png`, fullPage: true });
const compact = await page.evaluate(() => ({ document: document.documentElement.scrollHeight, viewport: innerHeight, card: document.querySelector('.decision-card').getBoundingClientRect().toJSON(), cardScroll: document.querySelector('.decision-card').scrollHeight, cardHeight: document.querySelector('.decision-card').clientHeight, bodyWidth: document.body.scrollWidth, width: innerWidth }));
console.log('COMPACT', JSON.stringify(compact));
await page.getByRole('button', { name: /Decisione 3: Cambio di programma/ }).click();
await page.getByRole('heading', { name: 'Fino a quando si può cancellare?' }).waitFor();
await page.waitForTimeout(650);
await page.screenshot({ path: `${output}/compact-long-question.png`, fullPage: true });
await context.close();

const mobile = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, deviceScaleFactor: 1, reducedMotion: 'reduce' });
const mobilePage = await mobile.newPage();
mobilePage.on('pageerror', error => errors.push(error.message));
await mobilePage.goto('http://127.0.0.1:5173/', { waitUntil: 'networkidle' });
await mobilePage.evaluate(() => document.fonts.ready);
await mobilePage.waitForTimeout(500);
await mobilePage.screenshot({ path: `${output}/mobile.png`, fullPage: true });
assert.equal(await mobilePage.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'No horizontal overflow on mobile');
await mobilePage.getByRole('button', { name: /Anche chi non ha un account/ }).click();
await mobilePage.getByRole('button', { name: 'Conferma decisione', exact: true }).click();
await mobilePage.getByRole('heading', { name: 'Quanto dura una prenotazione?' }).waitFor();
assert.equal(errors.length, 0, JSON.stringify(errors));
console.log('PASS: demo flow, cascade preview, decision reversal, persistence, export, unavailable core, compact desktop and mobile.');
await browser.close();
